name: CI/CD to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest

      - name: Start Minikube
        run: minikube start --driver=docker

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Build Docker image
        run: docker build -t betterme-app:latest .

      - name: Run container
        run: docker run -d --name betterme-app betterme-app:latest

      - name: Run tests inside container
        run: docker exec betterme-app sh -c "echo 'Running tests' && ls -l"

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker build -t $DOCKER_USERNAME/betterme-app:latest .
          docker push $DOCKER_USERNAME/betterme-app:latest

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install betterme ./helm --set image.repository=$DOCKER_USERNAME/betterme-app --set image.tag=latest

      - name: Verify deployment
        run: kubectl get pods
