name: CI/CD to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest

      - name: Start Minikube
        run: minikube start --driver=docker

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Build and push Docker image
        run: |
          docker build -t betterme-app:latest .
          docker tag betterme-app:latest $DOCKER_USERNAME/betterme-app:latest
          docker push $DOCKER_USERNAME/betterme-app:latest

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install betterme ./helm --set image.repository=./betterme-app --set image.tag=latest

      - name: Verify deployment
        run: kubectl get pods
